### ISSUE TITLE
Add library for ESP32

### ISSUE THREAD

**Issue by userosos** [climateguard/CG-Anem#4]
Привет! Я не могу добавить устройство в ESPhome.
Скопировал в /esphome/cgAnem/ файлы cgAnem.cpp и cgAnem.h
Файл конфигурации esphome:
```
esphome:
  name: esp32
  friendly_name: ESP32
  libraries:
   - Wire
   - "ClimateGuard CG Anem"
   -  Arduino
  includes:
   - cgAnem/cgAnem.h
   - cgAnem/cgAnem.cpp
   
esp32:
  board: esp32dev
  framework:
    type: arduino

i2c:
  - id: bus_a
    sda: 32
    scl: 33
  - id: bus_b
    sda: 14
    scl: 15
    scan: true
  #  scan: true
......
sensor:
  - platform: custom
    lambda: |-
     auto CGAnem = new CG_Anem(0x11);
     App.register_component(CGAnem);
     return {CGAnem->temperature,CGAnem->airConsumption,CGAnem->airflowRate};
     
    sensors:
    - name: "Temperatura"
      id: CG_Anem_temperature
#      accuracy_decimals: 0.1
      unit_of_measurement: C
      state_class: measurement
    - name: "airConsumption"
      id: airConsumption
#      accuracy_decimals: 0.1
      unit_of_measurement: m^3/hour
      state_class: measurement
    - name: "airflowRate"
      id: airflowRate
#      accuracy_decimals: 0.1
      unit_of_measurement: m/s
      state_class: measurement
```
Но так не работает. т. к. библиотека все же не предназначена для ESPhome.

Нашел подобный проект где человек переделал библиотеку, но сам не смогу переделать:
https://github.com/maaad/RadSens1v2
